
name: Run Xray Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Xray
      run: |
        sudo apt update
        sudo apt install -y unzip curl
        curl -O https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
        unzip Xray-linux-64.zip
        mkdir /etc/xray
        cp geo* /etc/xray/
        cp xray /usr/local/bin/
        chmod +x /usr/local/bin/xray
        echo "$XRAY_CONFIG" > /etc/xray/config.json
        nohup xray run -c /etc/xray/config.json &

    - name: Show config
      run: echo "Xray is running!"
      env:
        XRAY_CONFIG: ${{ secrets.XRAY_CONFIG }}
